./zipNpush.sh activate_convo activate_convo
./zipNpush.sh block_convo block_convo
./zipNpush.sh collect_earnings collect_earnings
./zipNpush.sh create_community create_community
./zipNpush.sh create_convo create_convo
./zipNpush.sh create_message create_message
./zipNpush.sh create_post digitari_create_post
./zipNpush.sh dismiss_convo dismiss_convo
./zipNpush.sh donate_to_post donate_to_post
./zipNpush.sh finish_convo finish_convo
./zipNpush.sh follow_community follow_community
./zipNpush.sh follow_user follow_user
./zipNpush.sh transaction_accumulation transaction_accumulation
./zipNpush.sh unfollow_user unfollow_user
./zipNpush.sh unfollow_community unfollow_community
./zipNpush.sh update_profile_pic update_profile_pic
